version: '3.3'

volumes:
  local_postgres_data:


services:
  web:
    build:
      context: .
      dockerfile: compose/django/Dockerfile
    container_name: speakhunt_backend
    ports:
      - "7100:8000"
    command: python Call_Server.py
    restart: always
